'use strict';
const COMMAND_TYPES=Object.freeze({START_GOAL:'start_goal',CANCEL_GOAL:'cancel_goal',CANCEL_ALL:'cancel_all',SET_SLOT:'set_slot',CLEAR_SLOT:'clear_slot',REQUEST_INFO:'request_information',CONFIRM:'confirm',REJECT:'reject',ASK_ALTERNATIVE:'ask_alternative',RESUME_GOAL:'resume_goal',HANDOFF:'handoff',GRATITUDE:'gratitude',GREETING:'greeting',OUT_OF_SCOPE:'out_of_scope',MEDICAL_ALERT:'medical_alert',FRUSTRATION:'frustration'});
const GOAL_TYPES=Object.freeze({BOOKING:'booking',INFORMATION:'information',HUMAN:'human_handoff'});
const INFO_TOPICS=Object.freeze(['price','location','business_hours','services','promotion','contact','payment_methods','insurance','preparation','duration','parking','policies','specialists','other']);
const SLOT_NAMES=Object.freeze(['branch','service','clinical_reason','date','time_preference','selected_slot','patient','phone']);
function emptyTurn(){return{commands:[],conversation_act:'unknown',user_goals:[],sentiment:'neutral',requires_clarification:false,clarification:null,confidence:0,raw:null};}
function sanitizeCommand(i){if(!i||typeof i!=='object')return null;const type=String(i.type||'').trim();if(!Object.values(COMMAND_TYPES).includes(type))return null;const o={type};if(i.goal&&Object.values(GOAL_TYPES).includes(i.goal))o.goal=i.goal;if(i.slot&&SLOT_NAMES.includes(i.slot))o.slot=i.slot;if(i.topic&&INFO_TOPICS.includes(i.topic))o.topic=i.topic;if(i.value!==undefined)o.value=i.value;if(i.reference)o.reference=String(i.reference);if(i.reason)o.reason=String(i.reason);if(Number.isFinite(Number(i.confidence)))o.confidence=Number(i.confidence);return o;}
function sanitizeTurn(i){const o=emptyTurn();if(!i||typeof i!=='object')return o;o.commands=(Array.isArray(i.commands)?i.commands:[]).map(sanitizeCommand).filter(Boolean).slice(0,30);o.conversation_act=String(i.conversation_act||'unknown');o.user_goals=Array.isArray(i.user_goals)?i.user_goals.slice(0,10):[];o.sentiment=['neutral','positive','negative','frustrated','urgent'].includes(i.sentiment)?i.sentiment:'neutral';o.requires_clarification=Boolean(i.requires_clarification);o.clarification=i.clarification&&typeof i.clarification==='object'?i.clarification:null;o.confidence=Math.max(0,Math.min(1,Number(i.confidence||0)));o.raw=i;return o;}
module.exports={COMMAND_TYPES,GOAL_TYPES,INFO_TOPICS,SLOT_NAMES,emptyTurn,sanitizeCommand,sanitizeTurn};
