'use strict';
const {GOAL_TYPES}=require('./command-schema');
function slot(value=null,o={}){return{value,status:o.status||(value===null?'missing':'inferred'),confidence:Number(o.confidence||(value===null?0:.7)),source_turn:o.source_turn||null,updated_at:new Date().toISOString(),previous:Array.isArray(o.previous)?o.previous.slice(-10):[]};}
function initialState(input={}){const s=input&&typeof input==='object'?input:{};const old=s.slots&&typeof s.slots==='object'?s.slots:{};const state={version:'v5',turn:Number(s.turn||0),mode:s.mode||'idle',active_goals:Array.isArray(s.active_goals)?s.active_goals:[],suspended_goals:Array.isArray(s.suspended_goals)?s.suspended_goals:[],completed_goals:Array.isArray(s.completed_goals)?s.completed_goals.slice(-20):[],slots:{},pending_questions:Array.isArray(s.pending_questions)?s.pending_questions:[],answered_questions:Array.isArray(s.answered_questions)?s.answered_questions.slice(-30):[],pending_actions:Array.isArray(s.pending_actions)?s.pending_actions:[],last_system_question:s.last_system_question||null,last_offer:s.last_offer||null,last_action:s.last_action||null,commitments:s.commitments&&typeof s.commitments==='object'?s.commitments:{},repair:s.repair||null,frustration_count:Number(s.frustration_count||0),no_progress_count:Number(s.no_progress_count||0),recent_turns:Array.isArray(s.recent_turns)?s.recent_turns.slice(-12):[],appointment_id:s.appointment_id||null,completed_at:s.completed_at||null};for(const n of ['branch','service','clinical_reason','date','time_preference','selected_slot','patient','phone'])state.slots[n]=old[n]&&typeof old[n]==='object'?{...slot(),...old[n]}:slot(s[n]??null,{status:s[n]?'inferred':'missing',confidence:s[n]?.5:0});if(s.branch_key&&!state.slots.branch.value)state.slots.branch=slot(s.branch_key);if(s.service_id&&!state.slots.service.value)state.slots.service=slot({id:String(s.service_id),name:s.service_name||null});if(s.patient&&!state.slots.patient.value)state.slots.patient=slot(s.patient);if(s.phone&&!state.slots.phone.value)state.slots.phone=slot(s.phone);if(s.date&&!state.slots.date.value)state.slots.date=slot(s.date);if(s.selected_slot&&!state.slots.selected_slot.value)state.slots.selected_slot=slot(s.selected_slot);return state;}
function goalId(t){return`${t}:${Date.now()}:${Math.random().toString(36).slice(2,8)}`;}
function startGoal(s,t,data={}){let g=s.active_goals.find(x=>x.type===t&&x.status==='active');if(g){g.data={...(g.data||{}),...data};return g;}g={id:goalId(t),type:t,status:'active',created_at:new Date().toISOString(),data:{...data}};s.active_goals.push(g);updateMode(s);return g;}
function completeGoal(s,t,result={}){s.active_goals=s.active_goals.filter(g=>{if(g.type===t){s.completed_goals.push({...g,status:'completed',result,completed_at:new Date().toISOString()});return false;}return true;});updateMode(s);}
function cancelGoal(s,t){s.active_goals=s.active_goals.filter(g=>g.type!==t);s.pending_questions=s.pending_questions.filter(q=>q.goal!==t);if(t===GOAL_TYPES.BOOKING)clearBooking(s);updateMode(s);}
function cancelAll(s){const p=s.slots.phone?.value||null;const n=initialState();if(p)n.slots.phone=slot(p,{status:'known',confidence:1});return n;}
function setSlot(s,n,v,m={}){if(!(n in s.slots)||v===undefined||v===null||v==='')return false;const c=s.slots[n];if(JSON.stringify(c.value)===JSON.stringify(v))return false;const prev=[...(c.previous||[])];if(c.value!==null)prev.push({value:c.value,status:c.status});s.slots[n]=slot(v,{status:m.status||'inferred',confidence:m.confidence||.75,source_turn:s.turn,previous:prev});if(['branch','service','date','time_preference'].includes(n)){clearSlot(s,'selected_slot');s.last_offer=null;}if(n==='branch')clearSlot(s,'service');return true;}
function clearSlot(s,n){if(n in s.slots)s.slots[n]=slot(null,{previous:s.slots[n]?.previous||[]});}
function confirmSlot(s,n){if(s.slots[n]?.value!==null){s.slots[n].status='confirmed';s.slots[n].confidence=1;}}
function value(s,n){return s.slots[n]?.value??null;}
function hasGoal(s,t){return s.active_goals.some(g=>g.type===t&&g.status==='active');}
function addQuestion(s,q){const k=`${q.goal||''}:${q.topic||q.slot||''}`;if(!s.pending_questions.some(x=>`${x.goal||''}:${x.topic||x.slot||''}`===k))s.pending_questions.push({id:`${k}:${Date.now()}`,status:'pending',...q});}
function resolveQuestion(s,p,a){s.pending_questions=s.pending_questions.filter(q=>{if(p(q)){s.answered_questions.push({...q,status:'answered',answer:a});return false;}return true;});}
function clearBooking(s){for(const n of ['branch','service','clinical_reason','date','time_preference','selected_slot','patient'])clearSlot(s,n);s.last_offer=null;delete s.commitments.booking_confirmed;}
function bookingMissing(s){return['branch','service','date','selected_slot','phone','patient'].filter(n=>!value(s,n));}
function updateMode(s){const b=hasGoal(s,GOAL_TYPES.BOOKING),i=hasGoal(s,GOAL_TYPES.INFORMATION);s.mode=b&&i?'mixed':b?'booking':i?'information':'idle';}
function recordTurn(s,u,i,a,r){s.turn+=1;const fp=JSON.stringify({mode:s.mode,goals:s.active_goals.map(g=>g.type).sort(),slots:Object.fromEntries(Object.entries(s.slots).map(([k,v])=>[k,v.value])),pending:s.pending_questions.map(q=>q.topic||q.slot).sort(),action:a?.type||null});const prev=s.recent_turns.at(-1);s.no_progress_count=prev&&prev.fingerprint===fp&&prev.reply===r?s.no_progress_count+1:0;s.recent_turns.push({turn:s.turn,user:String(u||''),interpretation:i,action:a,reply:r,fingerprint:fp});s.recent_turns=s.recent_turns.slice(-12);s.last_action=a||null;}
module.exports={slot,initialState,startGoal,completeGoal,cancelGoal,cancelAll,setSlot,clearSlot,confirmSlot,value,hasGoal,addQuestion,resolveQuestion,clearBooking,bookingMissing,updateMode,recordTurn};
