'use strict';
const Module=require('module');
const originalLoad=Module._load;
Module._load=function(request,parent,isMain){
  if(request==='../booking-engine') return {
    getServices:async()=>[],
    computeAvailability:async()=>({slots:[]}),
    createAppointmentTransactional:async()=>({id:1,patient:'Test',date:'2026-08-03',start_time:'11:00'})
  };
  return originalLoad.apply(this,arguments);
};
process.env.RECEPTIONIST_V5_USE_AI='false';const assert=require('assert'),S=require('../backend/modules/receptionist-v5/dialogue-state'),{fallbackInterpret}=require('../backend/modules/receptionist-v5/fallback-interpreter'),{applyGlobalPatterns}=require('../backend/modules/receptionist-v5/conversation-patterns'),{applyTurnCommands}=require('../backend/modules/receptionist-v5/flow-engine'),{nextPolicy}=require('../backend/modules/receptionist-v5/policy-engine'),T=require('../backend/modules/receptionist-v5/tool-registry');const context={branches:[{branch_key:'sucursal_1',name:'Victoria'},{branch_key:'sucursal_2',name:'Condesa'}],services:[{id:'1',name:'Consulta general'},{id:'2',name:'Ortodoncia / brackets'},{id:'3',name:'Limpieza dental'}]};function apply(s,t){const turn=fallbackInterpret(t,s),p=applyGlobalPatterns(s,turn);s=p.state;if(!p.terminal)applyTurnCommands(s,turn,context);return{state:s,turn,terminal:p.terminal}}
let s=S.initialState(),o=apply(s,'Quiero informacion donde se ubican y que costo tiene la consulta quiero revisarme los brackets');s=o.state;assert.equal(s.mode,'information');assert.equal(S.hasGoal(s,'booking'),false);assert.equal(s.pending_questions.length,2);assert.equal(S.value(s,'service').id,'1');assert.equal(S.value(s,'clinical_reason'),'revisión de brackets');console.log('✅ información compleja sin iniciar cita');o=apply(s,'Condesa');s=o.state;assert.equal(S.value(s,'branch'),'sucursal_2');assert.equal(s.pending_questions.length,2);console.log('✅ sucursal corta conserva preguntas');assert.equal(T.matchService(context.services,'consulta','revisión de brackets').id,'1');console.log('✅ brackets selecciona consulta');o=apply(s,'Cancelar');s=o.state;assert.equal(o.terminal,true);assert.equal(s.mode,'idle');assert.equal(s.pending_questions.length,0);assert.equal(S.value(s,'branch'),null);console.log('✅ cancelar limpia todo');s=S.initialState();o=apply(s,'Quiero agendar limpieza en Victoria');s=o.state;assert.equal(s.mode,'booking');assert.equal(S.value(s,'branch'),'sucursal_1');assert.equal(S.value(s,'service').id,'3');assert.equal(nextPolicy(s).slot,'date');console.log('✅ booking en cualquier orden');S.setSlot(s,'date','2026-08-03');assert.equal(nextPolicy(s).type,'check_availability');console.log('✅ disponibilidad con precondiciones');S.setSlot(s,'selected_slot',{date:'2026-08-03',start_time:'11:00'});S.setSlot(s,'phone','5202713253');S.setSlot(s,'patient','Hannah Sofía');assert.equal(nextPolicy(s).type,'request_booking_confirmation');console.log('✅ exige confirmación final');s.last_system_question={type:'booking_confirmation'};o=apply(s,'Sí');s=o.state;assert.equal(s.commitments.booking_confirmed,true);assert.equal(nextPolicy(s).type,'create_appointment');console.log('✅ sí depende de última pregunta');s=S.initialState();o=apply(s,'Dónde están y cuánto cuesta la consulta y además quiero agendar');s=o.state;assert.equal(S.hasGoal(s,'information'),true);assert.equal(S.hasGoal(s,'booking'),true);assert.equal(s.mode,'mixed');console.log('✅ objetivos mixtos');s=S.initialState();o=apply(s,'No me entiendes, ya me dijiste eso');s=o.state;assert.equal(s.repair.type,'frustration');console.log('✅ frustración global');console.log('\n9/9 pruebas V5 pasaron.');
